# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../Qt/filter_sky.ui'
#
# Created: Sun Sep  3 20:45:34 2017
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_filter_sky(object):
    def setupUi(self, filter_sky):
        filter_sky.setObjectName("filter_sky")
        filter_sky.resize(689, 682)
        filter_sky.setMinimumSize(QtCore.QSize(689, 682))
        filter_sky.setMaximumSize(QtCore.QSize(689, 682))
        self.centralWidget = QtWidgets.QWidget(filter_sky)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.Main_page = QtWidgets.QWidget()
        self.Main_page.setObjectName("Main_page")
        self.gridLayout = QtWidgets.QGridLayout(self.Main_page)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.Main_page)
        self.frame.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainPage_powerButton = QtWidgets.QPushButton(self.frame)
        self.mainPage_powerButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/plugging.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mainPage_powerButton.setIcon(icon)
        self.mainPage_powerButton.setIconSize(QtCore.QSize(48, 48))
        self.mainPage_powerButton.setFlat(True)
        self.mainPage_powerButton.setObjectName("mainPage_powerButton")
        self.verticalLayout.addWidget(self.mainPage_powerButton)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setEnabled(False)
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/transfer_function.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(48, 48))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/graphs.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.gridLayout.addWidget(self.frame, 0, 1, 2, 1)
        self.frame_2 = QtWidgets.QFrame(self.Main_page)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setMaximumSize(QtCore.QSize(500, 150))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/filter_logo.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout_2.addWidget(self.textBrowser_2)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label_11 = QtWidgets.QLabel(self.frame_6)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 150))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap(":/icons/logo_area 1.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.Main_page)
        self.frame_3.setStyleSheet("background-color: rgb(32, 74, 135);\n"
"border-color: rgb(0, 0, 0);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(2)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setMaximumSize(QtCore.QSize(62, 48))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/icons/welcome.svg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.gridLayout.addWidget(self.frame_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.Main_page)
        self.TF_page = QtWidgets.QWidget()
        self.TF_page.setObjectName("TF_page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.TF_page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_4 = QtWidgets.QLabel(self.TF_page)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Latin Modern Sans Demi Cond")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 2)
        self.frame_5 = QtWidgets.QFrame(self.TF_page)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.label_10 = QtWidgets.QLabel(self.frame_5)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_5.addWidget(self.lineEdit)
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_5.addWidget(self.lineEdit_2)
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.spinBox = QtWidgets.QSpinBox(self.frame_5)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_12 = QtWidgets.QLabel(self.frame_5)
        self.label_12.setEnabled(False)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_4.addWidget(self.lineEdit_4)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.frame_5)
        self.label_13.setEnabled(False)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_8.addWidget(self.label_13)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_8.addWidget(self.lineEdit_5)
        self.gridLayout_4.addLayout(self.verticalLayout_8, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comboBox = QtWidgets.QComboBox(self.frame_5)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_5)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_3.addWidget(self.checkBox_2)
        self.checkBox = QtWidgets.QCheckBox(self.frame_5)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_3.addWidget(self.checkBox)
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_5)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_3.addWidget(self.checkBox_3)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 4, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        self.label_8.setEnabled(False)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 5, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_4.addWidget(self.lineEdit_3, 6, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 7, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_5)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/calculator.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_6.addWidget(self.pushButton_5)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 8, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_5, 1, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.TF_page)
        self.frame_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_7.setEnabled(False)
        self.pushButton_7.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/tools-and-utensils.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon5)
        self.pushButton_7.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_6.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_8.setEnabled(False)
        self.pushButton_8.setText("")
        self.pushButton_8.setIcon(icon1)
        self.pushButton_8.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_6.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_9.setEnabled(False)
        self.pushButton_9.setText("")
        self.pushButton_9.setIcon(icon2)
        self.pushButton_9.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_9.setFlat(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_6.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_10.setEnabled(False)
        self.pushButton_10.setText("")
        self.pushButton_10.setIcon(icon3)
        self.pushButton_10.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_10.setFlat(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_6.addWidget(self.pushButton_10)
        self.pushButton_22 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_22.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/reply.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_22.setIcon(icon6)
        self.pushButton_22.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_22.setFlat(True)
        self.pushButton_22.setObjectName("pushButton_22")
        self.verticalLayout_6.addWidget(self.pushButton_22)
        self.gridLayout_5.addWidget(self.frame_4, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.TF_page)
        self.System_page = QtWidgets.QWidget()
        self.System_page.setObjectName("System_page")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.System_page)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_10 = QtWidgets.QFrame(self.System_page)
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 68))
        self.frame_10.setStyleSheet("background-color: rgb(32, 74, 135);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_10.setLineWidth(2)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_19 = QtWidgets.QLabel(self.frame_10)
        self.label_19.setMaximumSize(QtCore.QSize(48, 48))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap(":/icons/computer.svg"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_11.addWidget(self.label_19)
        self.label_14 = QtWidgets.QLabel(self.frame_10)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Latin Modern Sans Demi Cond")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: rgb(32, 74, 135);\n"
"color: rgb(238, 238, 236);")
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_11.addWidget(self.label_14)
        self.verticalLayout_9.addWidget(self.frame_10)
        self.frame_7 = QtWidgets.QFrame(self.System_page)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_16.setEnabled(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/hot-thermometer.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_16.setIcon(icon7)
        self.pushButton_16.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_16.setFlat(True)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_7.addWidget(self.pushButton_16)
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_15.setEnabled(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/tank.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_15.setIcon(icon8)
        self.pushButton_15.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_15.setFlat(True)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_7.addWidget(self.pushButton_15)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_19 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_19.setEnabled(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_19.setIcon(icon9)
        self.pushButton_19.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_19.setFlat(True)
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_8.addWidget(self.pushButton_19)
        self.pushButton_20 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_20.setEnabled(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/gas-pipe.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_20.setIcon(icon10)
        self.pushButton_20.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_20.setFlat(True)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_8.addWidget(self.pushButton_20)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_18 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_18.setEnabled(False)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/industrial-robot.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_18.setIcon(icon11)
        self.pushButton_18.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_18.setFlat(True)
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_9.addWidget(self.pushButton_18)
        self.pushButton_17 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_17.setEnabled(False)
        self.pushButton_17.setIcon(icon11)
        self.pushButton_17.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_17.setFlat(True)
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_9.addWidget(self.pushButton_17)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.verticalLayout_9.addWidget(self.frame_7)
        self.stackedWidget.addWidget(self.System_page)
        self.Elements_TF = QtWidgets.QWidget()
        self.Elements_TF.setObjectName("Elements_TF")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.Elements_TF)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.label_78 = QtWidgets.QLabel(self.Elements_TF)
        self.label_78.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Latin Modern Sans Demi Cond")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_78.setFont(font)
        self.label_78.setAlignment(QtCore.Qt.AlignCenter)
        self.label_78.setObjectName("label_78")
        self.gridLayout_25.addWidget(self.label_78, 0, 0, 1, 2)
        self.frame_44 = QtWidgets.QFrame(self.Elements_TF)
        self.frame_44.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_44.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_44.setObjectName("frame_44")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.frame_44)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.verticalLayout_47 = QtWidgets.QVBoxLayout()
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        self.label_79 = QtWidgets.QLabel(self.frame_44)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_79.setFont(font)
        self.label_79.setObjectName("label_79")
        self.verticalLayout_47.addWidget(self.label_79)
        self.label_80 = QtWidgets.QLabel(self.frame_44)
        self.label_80.setObjectName("label_80")
        self.verticalLayout_47.addWidget(self.label_80)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.frame_44)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.verticalLayout_47.addWidget(self.lineEdit_26)
        self.label_81 = QtWidgets.QLabel(self.frame_44)
        self.label_81.setObjectName("label_81")
        self.verticalLayout_47.addWidget(self.label_81)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.frame_44)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.verticalLayout_47.addWidget(self.lineEdit_27)
        self.label_82 = QtWidgets.QLabel(self.frame_44)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_82.setFont(font)
        self.label_82.setObjectName("label_82")
        self.verticalLayout_47.addWidget(self.label_82)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_83 = QtWidgets.QLabel(self.frame_44)
        self.label_83.setObjectName("label_83")
        self.horizontalLayout_43.addWidget(self.label_83)
        self.spinBox_6 = QtWidgets.QSpinBox(self.frame_44)
        self.spinBox_6.setObjectName("spinBox_6")
        self.horizontalLayout_43.addWidget(self.spinBox_6)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem6)
        self.verticalLayout_47.addLayout(self.horizontalLayout_43)
        self.gridLayout_24.addLayout(self.verticalLayout_47, 0, 0, 1, 1)
        self.verticalLayout_48 = QtWidgets.QVBoxLayout()
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        self.label_84 = QtWidgets.QLabel(self.frame_44)
        self.label_84.setEnabled(False)
        self.label_84.setObjectName("label_84")
        self.verticalLayout_48.addWidget(self.label_84)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.frame_44)
        self.lineEdit_28.setEnabled(False)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.verticalLayout_48.addWidget(self.lineEdit_28)
        self.gridLayout_24.addLayout(self.verticalLayout_48, 1, 0, 1, 1)
        self.verticalLayout_49 = QtWidgets.QVBoxLayout()
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        self.label_85 = QtWidgets.QLabel(self.frame_44)
        self.label_85.setEnabled(False)
        self.label_85.setObjectName("label_85")
        self.verticalLayout_49.addWidget(self.label_85)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.frame_44)
        self.lineEdit_29.setEnabled(False)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.verticalLayout_49.addWidget(self.lineEdit_29)
        self.gridLayout_24.addLayout(self.verticalLayout_49, 2, 0, 1, 1)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.comboBox_6 = QtWidgets.QComboBox(self.frame_44)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.horizontalLayout_44.addWidget(self.comboBox_6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_44.addItem(spacerItem7)
        self.gridLayout_24.addLayout(self.horizontalLayout_44, 3, 0, 1, 1)
        self.verticalLayout_50 = QtWidgets.QVBoxLayout()
        self.verticalLayout_50.setObjectName("verticalLayout_50")
        self.checkBox_16 = QtWidgets.QCheckBox(self.frame_44)
        self.checkBox_16.setObjectName("checkBox_16")
        self.verticalLayout_50.addWidget(self.checkBox_16)
        self.checkBox_17 = QtWidgets.QCheckBox(self.frame_44)
        self.checkBox_17.setObjectName("checkBox_17")
        self.verticalLayout_50.addWidget(self.checkBox_17)
        self.checkBox_18 = QtWidgets.QCheckBox(self.frame_44)
        self.checkBox_18.setObjectName("checkBox_18")
        self.verticalLayout_50.addWidget(self.checkBox_18)
        self.gridLayout_24.addLayout(self.verticalLayout_50, 4, 0, 1, 1)
        self.label_86 = QtWidgets.QLabel(self.frame_44)
        self.label_86.setEnabled(False)
        self.label_86.setObjectName("label_86")
        self.gridLayout_24.addWidget(self.label_86, 5, 0, 1, 1)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.frame_44)
        self.lineEdit_30.setEnabled(False)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.gridLayout_24.addWidget(self.lineEdit_30, 6, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_24.addItem(spacerItem8, 7, 0, 1, 1)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_45.addItem(spacerItem9)
        self.pushButton_106 = QtWidgets.QPushButton(self.frame_44)
        self.pushButton_106.setIcon(icon4)
        self.pushButton_106.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_106.setObjectName("pushButton_106")
        self.horizontalLayout_45.addWidget(self.pushButton_106)
        self.gridLayout_24.addLayout(self.horizontalLayout_45, 8, 0, 1, 1)
        self.gridLayout_25.addWidget(self.frame_44, 1, 0, 1, 1)
        self.frame_45 = QtWidgets.QFrame(self.Elements_TF)
        self.frame_45.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_45.setStyleSheet("")
        self.frame_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.verticalLayout_51 = QtWidgets.QVBoxLayout(self.frame_45)
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.pushButton_107 = QtWidgets.QPushButton(self.frame_45)
        self.pushButton_107.setEnabled(False)
        self.pushButton_107.setText("")
        self.pushButton_107.setIcon(icon5)
        self.pushButton_107.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_107.setFlat(True)
        self.pushButton_107.setObjectName("pushButton_107")
        self.verticalLayout_51.addWidget(self.pushButton_107)
        self.pushButton_108 = QtWidgets.QPushButton(self.frame_45)
        self.pushButton_108.setEnabled(False)
        self.pushButton_108.setText("")
        self.pushButton_108.setIcon(icon1)
        self.pushButton_108.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_108.setFlat(True)
        self.pushButton_108.setObjectName("pushButton_108")
        self.verticalLayout_51.addWidget(self.pushButton_108)
        self.pushButton_109 = QtWidgets.QPushButton(self.frame_45)
        self.pushButton_109.setEnabled(False)
        self.pushButton_109.setText("")
        self.pushButton_109.setIcon(icon2)
        self.pushButton_109.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_109.setFlat(True)
        self.pushButton_109.setObjectName("pushButton_109")
        self.verticalLayout_51.addWidget(self.pushButton_109)
        self.pushButton_110 = QtWidgets.QPushButton(self.frame_45)
        self.pushButton_110.setEnabled(False)
        self.pushButton_110.setText("")
        self.pushButton_110.setIcon(icon3)
        self.pushButton_110.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_110.setFlat(True)
        self.pushButton_110.setObjectName("pushButton_110")
        self.verticalLayout_51.addWidget(self.pushButton_110)
        self.pushButton_111 = QtWidgets.QPushButton(self.frame_45)
        self.pushButton_111.setText("")
        self.pushButton_111.setIcon(icon6)
        self.pushButton_111.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_111.setFlat(True)
        self.pushButton_111.setObjectName("pushButton_111")
        self.verticalLayout_51.addWidget(self.pushButton_111)
        self.gridLayout_25.addWidget(self.frame_45, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.Elements_TF)
        self.TIC_TF = QtWidgets.QWidget()
        self.TIC_TF.setObjectName("TIC_TF")
        self.gridLayout_37 = QtWidgets.QGridLayout(self.TIC_TF)
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.label_137 = QtWidgets.QLabel(self.TIC_TF)
        self.label_137.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Latin Modern Sans Demi Cond")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_137.setFont(font)
        self.label_137.setAlignment(QtCore.Qt.AlignCenter)
        self.label_137.setObjectName("label_137")
        self.gridLayout_37.addWidget(self.label_137, 0, 0, 1, 2)
        self.frame_63 = QtWidgets.QFrame(self.TIC_TF)
        self.frame_63.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_63.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_63.setObjectName("frame_63")
        self.gridLayout_36 = QtWidgets.QGridLayout(self.frame_63)
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.verticalLayout_75 = QtWidgets.QVBoxLayout()
        self.verticalLayout_75.setObjectName("verticalLayout_75")
        self.label_129 = QtWidgets.QLabel(self.frame_63)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_129.setFont(font)
        self.label_129.setObjectName("label_129")
        self.verticalLayout_75.addWidget(self.label_129)
        self.label_130 = QtWidgets.QLabel(self.frame_63)
        self.label_130.setObjectName("label_130")
        self.verticalLayout_75.addWidget(self.label_130)
        self.lineEdit_48 = QtWidgets.QLineEdit(self.frame_63)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.verticalLayout_75.addWidget(self.lineEdit_48)
        self.label_131 = QtWidgets.QLabel(self.frame_63)
        self.label_131.setObjectName("label_131")
        self.verticalLayout_75.addWidget(self.label_131)
        self.lineEdit_49 = QtWidgets.QLineEdit(self.frame_63)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.verticalLayout_75.addWidget(self.lineEdit_49)
        self.label_132 = QtWidgets.QLabel(self.frame_63)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_132.setFont(font)
        self.label_132.setObjectName("label_132")
        self.verticalLayout_75.addWidget(self.label_132)
        self.horizontalLayout_64 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_64.setObjectName("horizontalLayout_64")
        self.label_133 = QtWidgets.QLabel(self.frame_63)
        self.label_133.setObjectName("label_133")
        self.horizontalLayout_64.addWidget(self.label_133)
        self.spinBox_11 = QtWidgets.QSpinBox(self.frame_63)
        self.spinBox_11.setObjectName("spinBox_11")
        self.horizontalLayout_64.addWidget(self.spinBox_11)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_64.addItem(spacerItem10)
        self.verticalLayout_75.addLayout(self.horizontalLayout_64)
        self.gridLayout_36.addLayout(self.verticalLayout_75, 0, 0, 1, 1)
        self.verticalLayout_76 = QtWidgets.QVBoxLayout()
        self.verticalLayout_76.setObjectName("verticalLayout_76")
        self.label_134 = QtWidgets.QLabel(self.frame_63)
        self.label_134.setEnabled(False)
        self.label_134.setObjectName("label_134")
        self.verticalLayout_76.addWidget(self.label_134)
        self.lineEdit_50 = QtWidgets.QLineEdit(self.frame_63)
        self.lineEdit_50.setEnabled(False)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.verticalLayout_76.addWidget(self.lineEdit_50)
        self.gridLayout_36.addLayout(self.verticalLayout_76, 1, 0, 1, 1)
        self.verticalLayout_77 = QtWidgets.QVBoxLayout()
        self.verticalLayout_77.setObjectName("verticalLayout_77")
        self.label_135 = QtWidgets.QLabel(self.frame_63)
        self.label_135.setEnabled(False)
        self.label_135.setObjectName("label_135")
        self.verticalLayout_77.addWidget(self.label_135)
        self.lineEdit_51 = QtWidgets.QLineEdit(self.frame_63)
        self.lineEdit_51.setEnabled(False)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.verticalLayout_77.addWidget(self.lineEdit_51)
        self.gridLayout_36.addLayout(self.verticalLayout_77, 2, 0, 1, 1)
        self.horizontalLayout_65 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_65.setObjectName("horizontalLayout_65")
        self.comboBox_10 = QtWidgets.QComboBox(self.frame_63)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.horizontalLayout_65.addWidget(self.comboBox_10)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_65.addItem(spacerItem11)
        self.gridLayout_36.addLayout(self.horizontalLayout_65, 3, 0, 1, 1)
        self.verticalLayout_78 = QtWidgets.QVBoxLayout()
        self.verticalLayout_78.setObjectName("verticalLayout_78")
        self.checkBox_28 = QtWidgets.QCheckBox(self.frame_63)
        self.checkBox_28.setObjectName("checkBox_28")
        self.verticalLayout_78.addWidget(self.checkBox_28)
        self.checkBox_29 = QtWidgets.QCheckBox(self.frame_63)
        self.checkBox_29.setObjectName("checkBox_29")
        self.verticalLayout_78.addWidget(self.checkBox_29)
        self.checkBox_30 = QtWidgets.QCheckBox(self.frame_63)
        self.checkBox_30.setObjectName("checkBox_30")
        self.verticalLayout_78.addWidget(self.checkBox_30)
        self.gridLayout_36.addLayout(self.verticalLayout_78, 4, 0, 1, 1)
        self.label_136 = QtWidgets.QLabel(self.frame_63)
        self.label_136.setEnabled(False)
        self.label_136.setObjectName("label_136")
        self.gridLayout_36.addWidget(self.label_136, 5, 0, 1, 1)
        self.lineEdit_52 = QtWidgets.QLineEdit(self.frame_63)
        self.lineEdit_52.setEnabled(False)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.gridLayout_36.addWidget(self.lineEdit_52, 6, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_36.addItem(spacerItem12, 7, 0, 1, 1)
        self.horizontalLayout_66 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_66.setObjectName("horizontalLayout_66")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_66.addItem(spacerItem13)
        self.pushButton_155 = QtWidgets.QPushButton(self.frame_63)
        self.pushButton_155.setIcon(icon4)
        self.pushButton_155.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_155.setObjectName("pushButton_155")
        self.horizontalLayout_66.addWidget(self.pushButton_155)
        self.gridLayout_36.addLayout(self.horizontalLayout_66, 8, 0, 1, 1)
        self.gridLayout_37.addWidget(self.frame_63, 1, 0, 1, 1)
        self.frame_64 = QtWidgets.QFrame(self.TIC_TF)
        self.frame_64.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_64.setStyleSheet("")
        self.frame_64.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_64.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_64.setObjectName("frame_64")
        self.verticalLayout_79 = QtWidgets.QVBoxLayout(self.frame_64)
        self.verticalLayout_79.setObjectName("verticalLayout_79")
        self.pushButton_156 = QtWidgets.QPushButton(self.frame_64)
        self.pushButton_156.setEnabled(False)
        self.pushButton_156.setText("")
        self.pushButton_156.setIcon(icon5)
        self.pushButton_156.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_156.setFlat(True)
        self.pushButton_156.setObjectName("pushButton_156")
        self.verticalLayout_79.addWidget(self.pushButton_156)
        self.pushButton_157 = QtWidgets.QPushButton(self.frame_64)
        self.pushButton_157.setEnabled(False)
        self.pushButton_157.setText("")
        self.pushButton_157.setIcon(icon1)
        self.pushButton_157.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_157.setFlat(True)
        self.pushButton_157.setObjectName("pushButton_157")
        self.verticalLayout_79.addWidget(self.pushButton_157)
        self.pushButton_158 = QtWidgets.QPushButton(self.frame_64)
        self.pushButton_158.setEnabled(False)
        self.pushButton_158.setText("")
        self.pushButton_158.setIcon(icon2)
        self.pushButton_158.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_158.setFlat(True)
        self.pushButton_158.setObjectName("pushButton_158")
        self.verticalLayout_79.addWidget(self.pushButton_158)
        self.pushButton_159 = QtWidgets.QPushButton(self.frame_64)
        self.pushButton_159.setEnabled(False)
        self.pushButton_159.setText("")
        self.pushButton_159.setIcon(icon3)
        self.pushButton_159.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_159.setFlat(True)
        self.pushButton_159.setObjectName("pushButton_159")
        self.verticalLayout_79.addWidget(self.pushButton_159)
        self.pushButton_160 = QtWidgets.QPushButton(self.frame_64)
        self.pushButton_160.setText("")
        self.pushButton_160.setIcon(icon6)
        self.pushButton_160.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_160.setFlat(True)
        self.pushButton_160.setObjectName("pushButton_160")
        self.verticalLayout_79.addWidget(self.pushButton_160)
        self.gridLayout_37.addWidget(self.frame_64, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.TIC_TF)
        self.horizontalLayout_3.addWidget(self.stackedWidget)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        filter_sky.setCentralWidget(self.centralWidget)

        self.retranslateUi(filter_sky)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton_15.clicked.connect(filter_sky.levelMainPage)
        self.pushButton_16.clicked.connect(filter_sky.temperatureMainPage)
        self.pushButton_20.clicked.connect(filter_sky.flowMainPage)
        self.pushButton_19.clicked.connect(filter_sky.pressureMainPage)
        self.mainPage_powerButton.clicked.connect(filter_sky.systemPage)
        QtCore.QMetaObject.connectSlotsByName(filter_sky)

    def retranslateUi(self, filter_sky):
        _translate = QtCore.QCoreApplication.translate
        filter_sky.setWindowTitle(_translate("filter_sky", "FilterSky"))
        self.textBrowser_2.setHtml(_translate("filter_sky", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">FilterSky é um <span style=\" font-style:italic;\">software</span> livre<span style=\" font-style:italic;\"> </span>idealizado para auxiliar os alunos e docentes na simulação de filtros digitais aplicados a sistemas e processos industriais.</p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Desenvolvido como projeto de iniciação científica por Matheus Nascimento, orientado pelo professor Oberdan Pinheiro , o <span style=\" font-style:italic;\">software </span>abrange  as áreas de controle de processos químicos, análise de sinais e sistemas e processamento de sinais digitais.</p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-style:italic;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">Esta aplicação é disponibilizada sob a </span><a href=\"https://opensource.org/licenses/BSD-3-Clause\"><span style=\" text-decoration: underline; color:#0000ff;\">3º cláusula da licença BSD de software. </span></a><span style=\" font-style:italic;\">Os ícones utilizados são de propriedade da empresa </span><a href=\"https://www.flaticon.com/privacy-policy\"><span style=\" text-decoration: underline; color:#0000ff;\">Flat Icon </span></a><span style=\" font-style:italic;\">e possuem todos os direitos reservados.</span></p></body></html>"))
        self.label_2.setText(_translate("filter_sky", "  IMPORTANTE:"))
        self.label_4.setText(_translate("filter_sky", "CARACTERÍSTICAS DA FUNÇÃO DE TRANSFERÊNCIA\n"
" DA MALHA DE TEMPERATURA"))
        self.label_7.setText(_translate("filter_sky", "Parâmetros:"))
        self.label_10.setText(_translate("filter_sky", "Ganho (k):"))
        self.label_9.setText(_translate("filter_sky", "Constante de tempo (Tc):"))
        self.label_5.setText(_translate("filter_sky", "Caracteristicas dos Polos: "))
        self.label_6.setText(_translate("filter_sky", "Nº"))
        self.label_12.setText(_translate("filter_sky", "Constante deAmortecimento (Xi):"))
        self.label_13.setText(_translate("filter_sky", "Período Natural de oscilação(Tn):"))
        self.comboBox.setItemText(0, _translate("filter_sky", "Todos Reais"))
        self.comboBox.setItemText(1, _translate("filter_sky", "Todos Imaginários"))
        self.checkBox_2.setText(_translate("filter_sky", "Integrator"))
        self.checkBox.setText(_translate("filter_sky", "Delay"))
        self.checkBox_3.setText(_translate("filter_sky", "Zero"))
        self.label_8.setText(_translate("filter_sky", "Tempo morto (Td):"))
        self.pushButton_5.setText(_translate("filter_sky", "SALVAR"))
        self.label_14.setText(_translate("filter_sky", "  DEFINIÇÃO DO SISTEMA"))
        self.pushButton_16.setText(_translate("filter_sky", "               TEMPERATURA"))
        self.pushButton_15.setText(_translate("filter_sky", "                    NÍVEL"))
        self.pushButton_19.setText(_translate("filter_sky", "                  PRESSÃO"))
        self.pushButton_20.setText(_translate("filter_sky", "                 VAZÃO"))
        self.pushButton_18.setText(_translate("filter_sky", "                 MALHA\n"
"                    DE\n"
"            CONTROLE I"))
        self.pushButton_17.setText(_translate("filter_sky", "                 MALHA\n"
"                    DE\n"
"            CONTROLE II"))
        self.label_78.setText(_translate("filter_sky", "CARACTERÍSTICAS DA FUNÇÃO DE TRANSFERÊNCIA\n"
" DA VÁLVULA 104"))
        self.label_79.setText(_translate("filter_sky", "Parâmetros:"))
        self.label_80.setText(_translate("filter_sky", "Ganho (k):"))
        self.label_81.setText(_translate("filter_sky", "Constante de tempo (Tc):"))
        self.label_82.setText(_translate("filter_sky", "Caracteristicas dos Polos: "))
        self.label_83.setText(_translate("filter_sky", "Nº"))
        self.label_84.setText(_translate("filter_sky", "Constante deAmortecimento (Xi):"))
        self.label_85.setText(_translate("filter_sky", "Período Natural de oscilação(Tn):"))
        self.comboBox_6.setItemText(0, _translate("filter_sky", "Todos Reais"))
        self.comboBox_6.setItemText(1, _translate("filter_sky", "Todos Imaginários"))
        self.checkBox_16.setText(_translate("filter_sky", "Integrator"))
        self.checkBox_17.setText(_translate("filter_sky", "Delay"))
        self.checkBox_18.setText(_translate("filter_sky", "Zero"))
        self.label_86.setText(_translate("filter_sky", "Tempo morto (Td):"))
        self.pushButton_106.setText(_translate("filter_sky", "SALVAR"))
        self.label_137.setText(_translate("filter_sky", "CARACTERÍSTICAS DA FUNÇÃO DE TRANSFERÊNCIA\n"
" DO CONTROLADOR TIC"))
        self.label_129.setText(_translate("filter_sky", "Parâmetros:"))
        self.label_130.setText(_translate("filter_sky", "Ganho (k):"))
        self.label_131.setText(_translate("filter_sky", "Constante de tempo (Tc):"))
        self.label_132.setText(_translate("filter_sky", "Caracteristicas dos Polos: "))
        self.label_133.setText(_translate("filter_sky", "Nº"))
        self.label_134.setText(_translate("filter_sky", "Constante deAmortecimento (Xi):"))
        self.label_135.setText(_translate("filter_sky", "Período Natural de oscilação(Tn):"))
        self.comboBox_10.setItemText(0, _translate("filter_sky", "Todos Reais"))
        self.comboBox_10.setItemText(1, _translate("filter_sky", "Todos Imaginários"))
        self.checkBox_28.setText(_translate("filter_sky", "Integrator"))
        self.checkBox_29.setText(_translate("filter_sky", "Delay"))
        self.checkBox_30.setText(_translate("filter_sky", "Zero"))
        self.label_136.setText(_translate("filter_sky", "Tempo morto (Td):"))
        self.pushButton_155.setText(_translate("filter_sky", "SALVAR"))

import filter_rc
